// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL-VLLLBy_B9PYR84JZ4sO5h7x2dyovdM',
    appId: '1:764951950984:web:55654bd746b9c030f2913d',
    messagingSenderId: '764951950984',
    projectId: 'horusqraccess-825c6',
    authDomain: 'horusqraccess-825c6.firebaseapp.com',
    databaseURL: 'https://horusqraccess-825c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'horusqraccess-825c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSp1fKE5s-qC67Jxk0OuagyLyZco1tUkY',
    appId: '1:764951950984:android:f76d7ab15379b6daf2913d',
    messagingSenderId: '764951950984',
    projectId: 'horusqraccess-825c6',
    databaseURL: 'https://horusqraccess-825c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'horusqraccess-825c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdN78-7NmGmYLAl7Hagd0q3-FgfM7FS6E',
    appId: '1:764951950984:ios:b745e60b2ab32e6cf2913d',
    messagingSenderId: '764951950984',
    projectId: 'horusqraccess-825c6',
    databaseURL: 'https://horusqraccess-825c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'horusqraccess-825c6.appspot.com',
    iosClientId: '764951950984-t5niif2dts86n88g9n5frtmpah3qd1p5.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdN78-7NmGmYLAl7Hagd0q3-FgfM7FS6E',
    appId: '1:764951950984:ios:b745e60b2ab32e6cf2913d',
    messagingSenderId: '764951950984',
    projectId: 'horusqraccess-825c6',
    databaseURL: 'https://horusqraccess-825c6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'horusqraccess-825c6.appspot.com',
    iosClientId: '764951950984-t5niif2dts86n88g9n5frtmpah3qd1p5.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrCode',
  );
}
